### ISSUE TITLE
Outputs not allowed twice

### ISSUE THREAD

**Issue by mayurpande** [thedirtyfew/dash-celery-mwe#1]
https://github.com/thedirtyfew/dash-celery-mwe/blob/999f986bd086d8535a668e777bd54455372e3d7d/app.py#L44

I am trying to doing something very similar with the polling aspect and celery and redis, however I am not allowed to have the output:

```
Output("poller", "max_intervals")
```

in two different callbacks as there is in your code.

```
dash==2.1.0
dash-bootstrap-components==1.0.3
dash-core-components==2.0.0
dash-cytoscape==0.3.0
dash-extensions==0.0.69
dash-html-components==2.0.0
dash-table==5.0.0
```

**Comment by emilhe** [comment]
I can see that the example is a bit old. It uses  `dash-extensions` to enable this behavior.  In more recent versions, you simply need to load the `MultiplexerTransform`,

https://github.com/thedirtyfew/dash-extensions#multiplexertransform

**Comment by mayurpande** [comment]
Thanks! I was just reading through the older version https://pypi.org/project/dash-extensions/0.0.1/ and realised.

**Comment by mayurpande** [comment]
Sorry one last question and I will close it as resolved. Does this mean I need to change all my callbacks to use the enrich callbacks, or is there a way I can integrate the two that I want to my existing app?

**Comment by emilhe** [comment]
If you just change your imports to be from `dash_extensions.enrich` (instead of `dash`) and replace the `Dash` object by `DashProxy` (or `Dash`) from `dash-extensions`, no other changes should be necessary.

**Comment by mayurpande** [comment]
Thanks @emilhe! Great tool!!

**Comment by emilhe** [comment]
Thanks!

**Comment by mayurpande** [comment]
Got another question, if you prefer I can put it on SO, as the polling callback keeps polling, if I am using the dcc.Loading it keeps getting reloaded as opposed to running smoothly as it does normally. Is there something in the multiplexer that I need to define? I followed the example https://github.com/thedirtyfew/dash-extensions/blob/master/examples/callback_multiplexer_proxy.py
