### ISSUE TITLE
invalid import for DashCallbackBlueprint

### ISSUE THREAD

**Issue by bsauvage1** [thedirtyfew/dash-celery-mwe#2]
Hello! 

Using Dash 2.1.0 and dash-extensions 0.0.71 on py39 -> what is the right import for DashCallbackBlueprint please?

Thank you

**Comment by emilhe** [comment]
I have just updated various dependencies to more recent versions and adopted the code accordingly. Does it solve your issue(s)?

**Comment by bsauvage1** [comment]
Great, indeed that import is gone. Can you please clarify why you import the below from dash_extensions.enrich as opposed as dash (which is what I would usually do) ? Is there any difference between the two ?
from dash_extensions.enrich import Dash, Output, Input, State, dcc, html
=>
from dash import Dash, Output, Input, State, dcc, html

**Comment by emilhe** [comment]
That’s because I am using the same property as `Output` in multiple callbacks. That’s not supported in vanilla Dash.

https://www.dash-extensions.com/getting-started/enrich

**Comment by bsauvage1** [comment]
Great, thank you. I will try and revert if any issue.
Closing for now

**Comment by bsauvage1** [comment]
So the app runs, but celery workers don't succeed. I'm running this on a windows machine (locally with waitress, without docker, without Redis, with RabbitMQ as both broker and backend).

-why explicitly import Flask and use it as server, instead of the usual declaration below (without passing the server=server argument inside Dash)? Isn't it the same thing ? I have tried and it returns callbacks errors, so out of curiosity I'd like to understand the difference between the two approaches.
app = Dash(xxx)
server = app.server

-while the app runs, the celery task shows issues. I'm using rabbitmq (and I see the queued messages increase  when pressing the button). I'm not using docker. I haven't installed Redis so I'm using Rabbitmq backend. I also launch celery workers. I get error.
in tasks.py: celery_app = Celery('tasks', broker='pyamqp://guest@localhost//', backend='rpc://', include=['cl.tasks'])
manual launch of celery workers: celery -A cl.tasks worker --loglevel=INFO
ERROR:
[2022-05-03 13:31:26,879: ERROR/MainProcess] Task handler raised error: ValueError('not enough values to unpack (expected 3, got 0)')
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\billiard\pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\celery\app\trace.py", line 635, in fast_trace_task
    tasks, accept, hostname = _loc
ValueError: not enough values to unpack (expected 3, got 0)

-instead of serving with Flask, I intend to serve with waitress which gives better results natively as it's multithreaded and production-grade. Does it make sense to use the celery setup with waitress server instances ? (I've tried and it still 'sort of works', but without adding blocking tasks to tasks.py I'm not sure it brings much benefit). This is how I've modified the app run (behind an nginx reverse proxy to handle the ssl security):
    waitress.serve(server, listen='127.0.0.1:80', url_scheme='https',
                   trusted_proxy_headers="forwarded",
                   trusted_proxy='xxx.xxx.xxx.xxx')

-my app is multipage, using the new structure released in the latest dash version. From a design point of view, what should I put inside the tasks.py? Should it be all the 'heavy functions' right now residing inside the individual pages? And if that's the case, should I have for each task some additional components to launch/poll/store result/store ref? (say I want to put 5 heavy jobs in tasks.py, that would be an additional 10 callbacks (launch/poll) and 10 containers.

Perhaps I was mistaken in my understanding of what celery solves, but what I was trying to put in place was multiprocess serving of the full app, not just multithreaded a-la waitress (and as I'm on windows, I can't use gunicorn). Please let me know if you think I'd be better 'served' by a different approach.
My apologies for all these questions and sorry to be such a noob. Please let me know if there would be a better forum to ask these.

**Comment by emilhe** [comment]
1) Those syntaxes should be equivalent

2) That sounds like some kind of configuration issue. It can be slightly tedious to _get things right_, that's why I bundled a complete example that runs with a single command. Then it's easy to get started without having to resolve configuration issues

3) When you say "serving with Flask", I guess you mean the development server? If so, then yes, it should **not** be used in production. You should use a WSGI server such as e.g. gunicorn or waitress. In any case, you should not run heavy tasks directly, these task should be offloaded elsewhere, e.g. using Celery. So if you have any heavy tasks, then **yes** Celery seems like a good fit

4) You should put all functions that are "heavy". There is no strict definition, but typically one would move tasks that take more than, say, 10 seconds (or maybe 30?) to complete

**Comment by bsauvage1** [comment]
thank you - I'll try to figure out the config issue by using your full example and "slowly deconstruct it" to see where things happen wrong on my end. I'll revert.

**Comment by bsauvage1** [comment]
and my apologies but to try your package, do I git clone then follow your instructions on the readme, or should it be done differently?  Sorry, deployment is a new thing to me.

**Comment by bsauvage1** [comment]
Found it! I had to add inside tasks.py:
os.environ.setdefault('FORKED_BY_MULTIPROCESSING', '1')
then messages get returned! This was a windows-specific issue as per:
https://stackoverflow.com/questions/45744992/celery-raises-valueerror-not-enough-values-to-unpack

So just to wrap it up: do I need 2 additional components for each celery task, a Store for results and an Interval for the poller ?

**Comment by emilhe** [comment]
Ah, yes. I haven't tried running on Windows, so it makes sense I haven't seen that error.

You could reuse some of the component (e.g. trigger multiple polls using the same `Interval `component), but otherwise yes; a `Store` component to hold the job reference, and an `Interval` component to check for updates.

**Comment by bsauvage1** [comment]
Thank you very much for all your answers, and for having created this super useful mwe!
